# Generated by Django 3.2.3 on 2021-06-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name_plural': 'Customer Transfers'},
        ),
    ]
